### ISSUE TITLE
Unhandled rejection RequestError: Error: connect ETIMEDOUT 104.20.135.15:443

### ISSUE THREAD

**Issue by eswarreddy43** [worr/node-imdb-api#50]
I am trying to integrate this API in my application by using following code
```
var imdb = require('imdb-api');
imdb.getById('tt0090190', {apiKey: 'XXXXXX'}).then(console.log);
```

But I am getting following error
```
Unhandled rejection RequestError: Error: connect ETIMEDOUT 104.20.135.15:443
    at new RequestError (C:\xampp\test\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\xampp\test\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\xampp\test\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\xampp\test\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\xampp\test\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I am trying to resolve from many hours. But not finding the proper solution.

Please guide me in this whether I am doing anything wrong in this. Thanks.

**Comment by worr** [comment]
Use a catch to grab errors via the promise interface, like any other promise.

so

```js
imdb.get(search).then((result) => {
  ...
}).catch((error) => {
  ...
});
```

This timeout isn't a problem with the library, your app is timing out talking to omdb. This could be caused by a number of things, and it's up to your app to defensively program against this.
